# Generated by Django 4.2.7 on 2023-12-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_decription_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.SmallIntegerField(default=0, verbose_name='номер версии')),
                ('version_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
